import React from 'react'
import {Table} from 'react-bulma-components/full'


export class DataTable extends React.Component{
  render (){
    return(
      <Table className="is-bordered is-striped is-hoverable">
        <thead>
          <tr>
            <th>Point</th>
            <th>IID</th>
            <th>STID</th>
            <th>NBO</th>
            <th>DPY</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
          <tr>
            <th>1</th>
            <td>38</td>
            <td>23</td>
            <td>12</td>
            <td>3</td>
          </tr>
        </tbody>
      </Table>
    )
  }
}
